---
- hosts: all
  connection: local

  vars_files:
    - "vars/{{ vars_choice }}.yml"

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
