---
- hosts: all
  connection: local

  vars_files:
    - "vars/{{ vars_choice }}.yml"

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - name: geerlingguy.mas
      when: app_store_enabled

  tasks:
    - include: tasks/ansible-setup.yml
    - name: Run .osx dotfiles.
      shell: ~/.osx
      changed_when: false
      when: configure_osx
    - name: install CF CLI plugins
      shell: cf install-plugin -f -r CF-Community "{{ item }}"
      with_items: "{{ cf_cli_plugins }}"
    - name: install AWS CLI
      shell: sudo pip install awscli --ignore-installed six
    - name: Add a line to /etc/shells to support latest bash install
      lineinfile:
        path: /etc/shells
        line: /usr/local/bin/bash
      become: true
    - name: Use latest bash for current user
      command: chsh -s /usr/local/bin/bash $USER
    - name: Use latest bash for root user
      command: chsh -s /usr/local/bin/bash
      become: true
    - name: Add bash completion support via bash_profile
      lineinfile:
        path: ~/.bash_profile
        line: export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
    - name: Add bash completion support via bash_profile
      lineinfile:
        path: ~/.bash_profile
        line: '[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"'

  vars_prompt:
    - name: "mas_password"
      prompt: "what is your mas_password?"
