---
- hosts: all
  connection: local

  vars_files:
    - "vars/{{ vars_choice }}.yml"

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - name: geerlingguy.mas
      when: app_store_enabled

  tasks:
    - include: tasks/ansible-setup.yml
    - name: Run .osx dotfiles.
      shell: ~/.osx
      changed_when: false
      when: configure_osx
    - name: install CF CLI plugins
      shell: cf install-plugin -f -r CF-Community "{{ item }}"
      with_items: "{{ cf_cli_plugins }}"
    - name: install AWS CLI
      shell: sudo pip install awscli --ignore-installed six

  vars_prompt:
    - name: "mas_password"
      prompt: "what is your mas_password?"
