---
- hosts: all
  connection: local

  vars_files:
    - "vars/{{ vars_choice }}.yml"

  roles:
    - java.homebrew
    - geerlingguy.dotfiles
    - name: geerlingguy.mas
      when: app_store_enabled

  tasks:
    - include: tasks/ansible-setup.yml
    - name: Run .osx dotfiles.
      shell: ~/.osx
      changed_when: false
      when: configure_osx
    - name: check CF CLI plugins
      stat: path="~/.cf/plugins/{{ item.binary }}"
      register: "cf_plugin_binary_exists"
      with_items: "{{ cf_cli_plugins }}"

    - debug: var=cf_plugin_binary_exists

    - debug: msg="item.item={{item.item}}, item.changed={{item.changed}}"
      with_items: "{{ cf_plugin_binary_exists.results }}"

    - name: install CF CLI plugins
      shell: cf install-plugin -f -r CF-Community "{{ item }}"
      when: item.stat.exists == False
      with_items: "{{ cf_plugin_binary_exists.results }}"

  vars_prompt:
    - name: "mas_password"
      prompt: "what is your mas_password?"
