---
- hosts: all
  connection: local

  vars_files:
    - "vars/{{ vars_choice }}.yml"

  roles:
    - java.homebrew
    - geerlingguy.dotfiles
    - name: geerlingguy.mas
      when: app_store_enabled

  tasks:
    - include: tasks/ansible-setup.yml
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false
      when: configure_osx

  vars_prompt:
    - name: "mas_password"
      prompt: "what is your mas_password?"

